// ════════════════════════════════════════════════════════════════════
// game/cardData.js — Card library and spreadsheet card definitions
// ════════════════════════════════════════════════════════════════════

import CARD_IMAGES from "./cardImages";

// ─── Snap ability reference library ──────────────────────────────────────────
export const SNAP_ABILITY_LIBRARY = [
  { name:"Abomination", ability:"\"Foolish rabble! You are beneath me!\"", release_date:"2022-05-24", series:"Starter/Pool 1" },
  { name:"Absorbing Man", ability:"On Reveal: If the last card you played has an On Reveal, copy its text. (if able)", release_date:"2022-11-22", series:"Series 3" },
  { name:"Adam Warlock", ability:"End of Turn: Draw a card if you're winning here. Otherwise, +1 Power.", release_date:"2022-05-24", series:"Series 3" },
  { name:"Aero", ability:"On Reveal: The last card your opponent played moves to this location.", release_date:"2022-05-24", series:"Series 3" },
  { name:"Agent 13", ability:"On Reveal: Add a random card to your hand.", release_date:"2022-05-24", series:"Series 3" },
  { name:"Agent Coulson", ability:"On Reveal: Add a random 4-Cost and 5-Cost card to your hand.", release_date:"2022-11-22", series:"Series 3" },
  { name:"Agent Venom", ability:"On Reveal: Set the Power of all cards in your deck to 3.", release_date:"2024-10-01", series:"Series 5" },
  { name:"Ajax", ability:"Ongoing: +1 Power for each card in play afflicted with negative Power.", release_date:"2024-07-16", series:"Series 5" },
  { name:"Alioth", ability:"On Reveal: Remove the text from all unrevealed enemy characters here.", release_date:"2023-09-12", series:"Series 5" },
  { name:"Ant Man", ability:"Ongoing: If your side of this location is full, +4 Power.", release_date:"2022-05-24", series:"Series 1" },
  { name:"Annihilus", ability:"On Reveal: Your cards with Power below 0 switch sides. Destroy those that can't.", release_date:"2023-11-21", series:"Series 5" },
  { name:"Arishem", ability:"Game Start: Shuffle 12 new cards into your deck. On turn 3, get +1 Max Energy.", release_date:"2024-07-02", series:"Series 5" },
  { name:"Arnim Zola", ability:"On Reveal: Destroy one of your other cards here to copy it at the other locations.", release_date:"2022-05-24", series:"Series 3" },
  { name:"Baron Zemo", ability:"On Reveal: Recruit a card that costs the least from your opponent's deck to your side of this location.", release_date:"2024-04-02", series:"Series 5" },
  { name:"Beta Ray Bill", ability:"On Reveal: Shuffle Stormbreaker into your deck.", release_date:"2024-01-30", series:"Series 5" },
  { name:"Black Panther", ability:"On Reveal: Double this card's Power.", release_date:"2022-11-08", series:"Series 3" },
  { name:"Blink", ability:"On Reveal: Swap the last card you played with a card that costs more from your deck.", release_date:"2024-05-07", series:"Series 5" },
  { name:"Blob", ability:"On Reveal: Merge cards from your deck into this until it gains 13 or more Power.", release_date:"2023-12-12", series:"Series 5" },
  { name:"Caiera", ability:"Ongoing: Your 1 and 6-Cost cards can't be destroyed.", release_date:"2024-01-02", series:"Series 5" },
  { name:"Cannonball", ability:"On Reveal: Move the highest-Power enemy card here away. If you can't, destroy it with a Rock.", release_date:"2024-03-19", series:"Series 5" },
  { name:"Cassandra Nova", ability:"On Reveal: Steal 1 Power from each card in your opponent's deck.", release_date:"2024-07-23", series:"Series 5" },
  { name:"Corvus Glaive", ability:"On Reveal: Discard 2 cards from your hand to get +1 Max Energy.", release_date:"2024-02-20", series:"Series 5" },
  { name:"Cull Obsidian", ability:"You can only play this where you have a 1-Cost card.", release_date:"2024-02-13", series:"Series 5" },
  { name:"Darkhawk", ability:"Ongoing: +2 Power for each card in your opponent's deck.", release_date:"2022-12-20", series:"Series 4" },
  { name:"Death", ability:"Costs 1 less for each card destroyed this game.", release_date:"2022-05-24", series:"Series 3" },
  { name:"Doctor Doom", ability:"On Reveal: Add a 5-Power DoomBot to each other location.", release_date:"2022-05-24", series:"Series 3" },
  { name:"Echo", ability:"After your opponent plays an Ongoing card here, remove its abilities.", release_date:"2023-07-18", series:"Series 4" },
  { name:"Elsa Bloodstone", ability:"Each card you play to fill your side of a location gains +2 Power.", release_date:"2023-10-03", series:"Series 5" },
  { name:"Galactus", ability:"On Reveal: If you're winning this location and this is your only card here, destroy all other locations.", release_date:"2022-12-06", series:"Series 5" },
  { name:"Gilgamesh", ability:"On Reveal: +1 Power for each of your other cards in play with increased Power.", release_date:"2024-06-04", series:"Series 5" },
  { name:"Gladiator", ability:"On Reveal: Add a card from your opponent's deck to their side of this location. If it has less Power, destroy it.", release_date:"2023-11-14", series:"Series 4" },
  { name:"Gwenpool", ability:"On Reveal: Pick a random character in your hand 3 times. Give +2 Power each time.", release_date:"2024-07-09", series:"Series 5" },
  { name:"Hela", ability:"On Reveal: For each different Cost among them, resurrect a card you discarded to a random location.", release_date:"2022-05-24", series:"Series 3" },
  { name:"High Evolutionary", ability:"Game Start: Unlock the potential of your cards with no abilities.", release_date:"2023-05-23", series:"Series 5" },
  { name:"Hope Summers", ability:"After you play a card here, you get +1 Energy next turn.", release_date:"2024-03-05", series:"Series 5" },
  { name:"Iron Lad", ability:"On Reveal: Copy the text of your deck's top card.", release_date:"2023-05-09", series:"Series 5" },
  { name:"Jeff the Baby Land Shark", ability:"You can move this once. Nothing can stop you from moving or playing this to any location.", release_date:"2023-04-18", series:"Series 5" },
  { name:"Knull", ability:"Ongoing: Has the combined Power of all cards destroyed this game.", release_date:"2022-12-13", series:"Series 4" },
  { name:"Loki", ability:"On Reveal: Replace your deck with your opponent's starting deck. Give those cards -1 Cost.", release_date:"2023-09-05", series:"Series 5" },
  { name:"Magneto", ability:"On Reveal: Move all enemy 3 and 4-Cost cards to this location.", release_date:"2022-05-24", series:"Series 3" },
  { name:"Makkari", ability:"End of Turn: Runs from your hand to a random location. (if possible)", release_date:"2024-06-18", series:"Series 5" },
  { name:"Mockingbird", ability:"Costs 1 less for each of your created cards in play.", release_date:"2024-03-12", series:"Series 5" },
  { name:"Ms. Marvel", ability:"Ongoing: Your adjacent locations with 2+ cards and no repeated Costs have +5 Power.", release_date:"2023-11-07", series:"Series 5" },
  { name:"Nebula", ability:"Each turn your opponent doesn't play a card here, +2 Power. (except the turn you play this)", release_date:"2023-05-02", series:"Series 5" },
  { name:"Nico Minoru", ability:"On Reveal: After you play your next card, cast a spell. (The spell changes each turn.)", release_date:"2023-10-24", series:"Series 5" },
  { name:"Nocturne", ability:"You can move this once. When this moves, replace its location with a random new one.", release_date:"2024-05-14", series:"Series 5" },
  { name:"Phastos", ability:"On Reveal: Give each card in your deck -1 Cost or +2 Power.", release_date:"2024-06-25", series:"Series 5" },
  { name:"Pixie", ability:"On Reveal: Shuffle the base Costs of all cards in your deck that started there.", release_date:"2024-03-05", series:"Series 5" },
  { name:"Proxima Midnight", ability:"When Discarded: This jumps to your lowest-Power location. (that isn't full)", release_date:"2024-02-27", series:"Series 5" },
  { name:"Red Hulk", ability:"End of Turn: If your opponent has unspent Energy, +3 Power. (if in hand or in play)", release_date:"2024-04-02", series:"Series 5" },
  { name:"Sersi", ability:"On Reveal: Transform your other characters here into random ones that cost 1 more. (if possible)", release_date:"2024-06-11", series:"Series 5" },
  { name:"Shaw (Sebastian)", ability:"When this permanently gains Power, gain +2 more Power. (wherever this is)", release_date:"2023-12-05", series:"Series 5" },
  { name:"Silver Surfer", ability:"On Reveal: Give your other 3-Cost cards +2 Power.", release_date:"2022-12-06", series:"Series 3" },
  { name:"Thanos", ability:"Game Start: Shuffle the six Infinity Stones into your deck.", release_date:"2022-12-06", series:"Series 5" },
  { name:"The Living Tribunal", ability:"Ongoing: Split your total Power evenly among all locations.", release_date:"2023-06-13", series:"Series 5" },
  { name:"Thena", ability:"End of Turn: +3 Power if you played (exactly) 2 cards.", release_date:"2024-06-04", series:"Series 5" },
  { name:"Wiccan", ability:"On Reveal: If you've spent all your Energy on previous turns, +2 Max Energy.", release_date:"2024-08-13", series:"Series 5" },
  { name:"X-23", ability:"When Discarded or Destroyed: Regenerate this at a random location and you get +1 Energy next turn.", release_date:"2023-08-22", series:"Series 5" },
];

// ─── All 77 Zany cards ────────────────────────────────────────────────────────
export const SPREADSHEET_CARDS = [
  { id:"c001", name:"Detective Scrotum", energy:4, clout: 5, abilityId:"  none", flavor:"Swamp-infected and on the case.", snapName:"Absorbing Man", abilityText:"On Reveal: If the last card you played has an On Reveal, copy its text.", imageUrl:CARD_IMAGES["c001"]||null },
  { id:"c002", name:"The Cretin", energy:2, clout: 0, abilityId:"  none", flavor:"Bra.", snapName:"Adam Warlock", abilityText:"End of Turn: Draw a card if you're winning here. Otherwise, +1 Power.", imageUrl:CARD_IMAGES["c002"]||null },
  { id:"c003", name:"Kotchy", energy:5, clout: 9, abilityId:" spark", flavor:"Pure raw power.", snapName:"Aero", abilityText:"On Reveal: The last card your opponent played moves to this location.", imageUrl:CARD_IMAGES["c003"]||null },
  { id:"c004", name:"Buttermilk Androgyna", energy:2, clout: 3, abilityId:"shadow", flavor:"Friend to all.", snapName:"Angela", abilityText:"After you play a card here, +1 Power.", imageUrl:CARD_IMAGES["c004"]||null },
  { id:"c005", name:"Mr. Plaigan", energy:5, clout: 8, abilityId:"  none", flavor:"Feeds on power.", snapName:"Annihilus", abilityText:"On Reveal: Your cards with Power below 0 switch sides. Destroy those that can't.", imageUrl:CARD_IMAGES["c005"]||null },
  { id:"c006", name:"Fenton All", energy:1, clout: 1, abilityId:"  none", flavor:"Grows in crowds.", snapName:"Ant Man", abilityText:"Ongoing: If your side of this location is full, +4 Power.", imageUrl:CARD_IMAGES["c006"]||null },
  { id:"c007", name:"The Warden", energy:6, clout: 8, abilityId:"  none", flavor:"Darkens all it touches.", snapName:"Apocalypse", abilityText:"When Discarded: Return this card with +4 Power.", imageUrl:CARD_IMAGES["c007"]||null },
  { id:"c008", name:"Peewee Dirtbag", energy:2, clout: 3, abilityId:" rally", flavor:"Pure static energy.", snapName:"Armor", abilityText:"Ongoing: Cards here can't be destroyed.", imageUrl:CARD_IMAGES["c008"]||null },
  { id:"c009", name:"Big Daddy Three Finger", energy:6, clout: 0, abilityId:"shadow", flavor:"", snapName:"Arnim Zola", abilityText:"On Reveal: Destroy one of your other cards here to copy it at the other locations.", imageUrl:CARD_IMAGES["c009"]||null },
  { id:"c010", name:"LeAntham Glass", energy:2, clout: 3, abilityId:" rally", flavor:"7 foot tall hockey player with violent tendencies.", snapName:"Baron Mordo", abilityText:"On Reveal: The top card of your opponent's deck costs 6 until turn 6.", imageUrl:CARD_IMAGES["c010"]||null },
  { id:"c011", name:"Boof Mudcat", energy:1, clout: 1, abilityId:" drain", flavor:"", snapName:"Bast", abilityText:"On Reveal: Set the Power of all cards in your hand to 3.", imageUrl:CARD_IMAGES["c011"]||null },
  { id:"c012", name:"Abassi King", energy:3, clout: 5, abilityId:" spark", flavor:"Name translates to \\\\\\", snapName:"Beast", abilityText:"On Reveal: Return your other cards here to your hand. They cost 1 less next turn.", imageUrl:CARD_IMAGES["c012"]||null },
  { id:"c013", name:"Tug McKracken", energy:3, clout: 2, abilityId:" drain", flavor:"", snapName:"Bishop", abilityText:"After you play a card, this gains +1 Power.", imageUrl:CARD_IMAGES["c013"]||null },
  { id:"c014", name:"Jordin Jinks", energy:5, clout: 8, abilityId:"  none", flavor:"", snapName:"Black Bolt", abilityText:"On Reveal: Discard the card that costs the least from your opponent's hand.", imageUrl:CARD_IMAGES["c014"]||null },
  { id:"c015", name:"Bubba Jumbo", energy:5, clout: 5, abilityId:"  none", flavor:"", snapName:"Black Panther", abilityText:"On Reveal: Double this card's Power.", imageUrl:CARD_IMAGES["c015"]||null },
  { id:"c016", name:"Fred Juggs", energy:3, clout: 3, abilityId:" surge", flavor:"", snapName:"Black Widow", abilityText:"Activate: Add a Widow's Bite to your opponent's hand.", imageUrl:CARD_IMAGES["c016"]||null },
  { id:"c017", name:"The Fishbanger", energy:1, clout: 3, abilityId:"  none", flavor:"", snapName:"Blade", abilityText:"On Reveal: Discard the rightmost card from your hand.", imageUrl:CARD_IMAGES["c017"]||null },
  { id:"c018", name:"JR Superbone", energy:5, clout: 3, abilityId:"  none", flavor:"", snapName:"Blue Marvel", abilityText:"Ongoing: Your other cards have +1 Power.", imageUrl:CARD_IMAGES["c018"]||null },
  { id:"c019", name:"Norm Phillibuster", energy:3, clout: 2, abilityId:" drain", flavor:"", snapName:"Brood", abilityText:"On Reveal: Add 2 Broodlings here with the same Power.", imageUrl:CARD_IMAGES["c019"]||null },
  { id:"c020", name:"Samson Slaughter", energy:2, clout: 4, abilityId:" drain", flavor:"", snapName:"Cable", abilityText:"On Reveal: Draw a card from your opponent's deck.", imageUrl:CARD_IMAGES["c020"]||null },
  { id:"c021", name:"Sniffy Arse", energy:5, clout: 5, abilityId:" drain", flavor:"", snapName:"Cannonball", abilityText:"On Reveal: Move the highest-Power enemy card here away. If you can't, destroy it.", imageUrl:CARD_IMAGES["c021"]||null },
  { id:"c022", name:"Logan Touchdown", energy:4, clout: 6, abilityId:" spark", flavor:"", snapName:"Captain Marvel", abilityText:"At the end of the game, move to a location that wins you the game.", imageUrl:CARD_IMAGES["c022"]||null },
  { id:"c023", name:"Buck Shindig", energy:2, clout: 2, abilityId:"  none", flavor:"", snapName:"Carnage", abilityText:"On Reveal: Destroy your other cards here. +2 Power for each destroyed.", imageUrl:CARD_IMAGES["c023"]||null },
  { id:"c024", name:"Bonald Brum", energy:3, clout: 0, abilityId:" rally", flavor:"Idiot president.", snapName:"Cassandra Nova", abilityText:"On Reveal: Steal 1 Power from each card in your opponent's deck.", imageUrl:CARD_IMAGES["c024"]||null },
  { id:"c025", name:"Hans Uberstein", energy:3, clout: 0, abilityId:" drain", flavor:"", snapName:"Cerebro", abilityText:"Ongoing: Your highest-Power cards have +3 Power.", imageUrl:CARD_IMAGES["c025"]||null },
  { id:"c026", name:"Souvenir Cheeseburger", energy:2, clout: 4, abilityId:"  none", flavor:"", snapName:"Cloak", abilityText:"On Reveal: Next turn, both players can move cards to this location.", imageUrl:CARD_IMAGES["c026"]||null },
  { id:"c027", name:"Shaquille Fofofo", energy:2, clout: 4, abilityId:"shadow", flavor:"Last name made with the Wendy's meal deal.", snapName:"Colossus", abilityText:"Ongoing: Can't be destroyed, moved, or have its Power reduced.", imageUrl:CARD_IMAGES["c027"]||null },
  { id:"c028", name:"LeTwink Piddlepants", energy:3, clout: 3, abilityId:"  none", flavor:"", snapName:"Cosmo", abilityText:"Ongoing: On Reveal abilities won't happen here.", imageUrl:CARD_IMAGES["c028"]||null },
  { id:"c029", name:"Jimmy Fushigi", energy:3, clout: 4, abilityId:" drain", flavor:"", snapName:"Crystal", abilityText:"On Reveal: Each player draws a card.", imageUrl:CARD_IMAGES["c029"]||null },
  { id:"c030", name:"Dan Schwartz", energy:2, clout: 2, abilityId:"  none", flavor:"", snapName:"Dagger", abilityText:"When this moves to a location, +2 Power for each enemy card there.", imageUrl:CARD_IMAGES["c030"]||null },
  { id:"c031", name:"Lucifer Melancholy", energy:2, clout: 3, abilityId:" drain", flavor:"", snapName:"Daredevil", abilityText:"On turn 5, you get to see your opponent's plays before you make your own.", imageUrl:CARD_IMAGES["c031"]||null },
  { id:"c032", name:"Jizzley Smeenish", energy:5, clout: 3, abilityId:" surge", flavor:"", snapName:"Darkhawk", abilityText:"Ongoing: +2 Power for each card in your opponent's deck.", imageUrl:CARD_IMAGES["c032"]||null },
  { id:"c033", name:"Garth Ponce", energy:1, clout: 1, abilityId:"  none", flavor:"Pink hair, karen cut, green eyeshadow.", snapName:"Deadpool", abilityText:"When Destroyed: Return this to your hand with double the Power.", imageUrl:CARD_IMAGES["c033"]||null },
  { id:"c034", name:"Venus Velociraptor M", energy:8, clout:12, abilityId:"  none", flavor:"", snapName:"Death", abilityText:"Costs 1 less for each card destroyed this game.", imageUrl:CARD_IMAGES["c034"]||null },
  { id:"c035", name:"General Doggins", energy:3, clout: 5, abilityId:" spark", flavor:"", snapName:"Deathlok", abilityText:"On Reveal: Destroy your other cards here.", imageUrl:CARD_IMAGES["c035"]||null },
  { id:"c036", name:"Basketball Mouse", energy:3, clout: 8, abilityId:"  none", flavor:"", snapName:"Debrii", abilityText:"On Reveal: Add a Rock to each other location.", imageUrl:CARD_IMAGES["c036"]||null },
  { id:"c037", name:"Cedric The Black Cedar Shingle", energy:5, clout: 4, abilityId:"shadow", flavor:"", snapName:"Devil Dinosaur", abilityText:"Ongoing: +2 Power for each card in your hand.", imageUrl:CARD_IMAGES["c037"]||null },
  { id:"c038", name:"Pregnant Woman Getting a Tattoo", energy:6, clout: 5, abilityId:" drain", flavor:"PSA: Do not do this!", snapName:"Doctor Doom", abilityText:"On Reveal: Add a 5-Power Bot to each other location.", imageUrl:CARD_IMAGES["c038"]||null },
  { id:"c039", name:"Meowsly McBirdie", energy:4, clout: 8, abilityId:"  none", flavor:"", snapName:"Doctor Octopus", abilityText:"On Reveal: Pull the lowest-Power card from your opponent's hand to their side here.", imageUrl:CARD_IMAGES["c039"]||null },
  { id:"c040", name:"Mini Miner", energy:2, clout: 3, abilityId:"shadow", flavor:"", snapName:"Doctor Strange", abilityText:"On Reveal: Move your highest-Power cards to this location.", imageUrl:CARD_IMAGES["c040"]||null },
  { id:"c041", name:"Wakanda Ellen", energy:4, clout: 1, abilityId:"  none", flavor:"", snapName:"Dracula", abilityText:"At the end of the game, discard a card from your hand to gain its Power.", imageUrl:CARD_IMAGES["c041"]||null },
  { id:"c042", name:"Congressman Joe Jonas", energy:4, clout: 5, abilityId:"  none", flavor:"", snapName:"Drax", abilityText:"On Reveal: If your opponent played a card here this turn, +4 Power.", imageUrl:CARD_IMAGES["c042"]||null },
  { id:"c043", name:"Podcast Squirrel", energy:1, clout: 2, abilityId:" rally", flavor:"", snapName:"Echo", abilityText:"After your opponent plays an Ongoing card here, remove its abilities.", imageUrl:CARD_IMAGES["c043"]||null },
  { id:"c044", name:"Goblin Addict", energy:3, clout: 5, abilityId:"  none", flavor:"", snapName:"Elsa Bloodstone", abilityText:"Each card you play to fill your side of a location gains +2 Power.", imageUrl:CARD_IMAGES["c044"]||null },
  { id:"c045", name:"Medevial Basketball Cat", energy:5, clout: 8, abilityId:"  none", flavor:"", snapName:"Enchantress", abilityText:"On Reveal: Remove the abilities from all Ongoing cards here.", imageUrl:CARD_IMAGES["c045"]||null },
  { id:"c046", name:"Timuoxi Cha le Mei", energy:2, clout: 3, abilityId:"shadow", flavor:"", snapName:"Falcon", abilityText:"On Reveal: Return your 1-Cost cards to your hand.", imageUrl:CARD_IMAGES["c046"]||null },
  { id:"c047", name:"Mr. Pants", energy:6, clout: 6, abilityId:" surge", flavor:"", snapName:"Galactus", abilityText:"On Reveal: If you're winning this location and this is your only card here, destroy all other locations.", imageUrl:CARD_IMAGES["c047"]||null },
  { id:"c048", name:"Disappointed Bison", energy:3, clout: 3, abilityId:"  none", flavor:"", snapName:"Gambit", abilityText:"On Reveal: Discard a card from your hand to destroy a random enemy card.", imageUrl:CARD_IMAGES["c048"]||null },
  { id:"c049", name:"Arabic Spongebob", energy:4, clout: 5, abilityId:"  none", flavor:"Enemy card text is now in Arabic.", snapName:"Ghost Rider", abilityText:"On Reveal: Bring back one of your discarded cards to this location.", imageUrl:CARD_IMAGES["c049"]||null },
  { id:"c050", name:"Sleepy Butterson", energy:5, clout: 9, abilityId:"  none", flavor:"", snapName:"Gilgamesh", abilityText:"On Reveal: +1 Power for each of your other cards in play with increased Power.", imageUrl:CARD_IMAGES["c050"]||null },
  { id:"c051", name:"Shane Gillis-Alexander", energy:3, clout: 8, abilityId:"  none", flavor:"1-cost cards are free next round.", snapName:"Gladiator", abilityText:"On Reveal: Add a card from your opponent's deck to their side here. If it has less Power, destroy it.", imageUrl:CARD_IMAGES["c051"]||null },
  { id:"c052", name:"Ted Boobz", energy:4, clout: 5, abilityId:"  none", flavor:"Other player cannot play cards here.", snapName:"Gwenpool", abilityText:"On Reveal: Pick a random card in your hand 3 times. Give +2 Power each time.", imageUrl:CARD_IMAGES["c052"]||null },
  { id:"c053", name:"Fatass Frank", energy:6, clout: 6, abilityId:" rally", flavor:"1 for every enemy card here.", snapName:"Hela", abilityText:"On Reveal: For each different Cost among them, bring back a discarded card to a random location.", imageUrl:CARD_IMAGES["c053"]||null },
  { id:"c054", name:"Eggbert", energy:4, clout: 7, abilityId:"  none", flavor:"End the game when Eggbert is destroyed.", snapName:"High Evolutionary", abilityText:"Game Start: Unlock the potential of your cards with no abilities.", imageUrl:CARD_IMAGES["c054"]||null },
  { id:"c055", name:"Tavern Wench", energy:3, clout: 4, abilityId:"  none", flavor:"Returns a played enemy card to their hand.", snapName:"Hope Summers", abilityText:"After you play a card here, you get +1 Energy next turn.", imageUrl:CARD_IMAGES["c055"]||null },
  { id:"c056", name:"The Biden Twins", energy:3, clout: 2, abilityId:"  none", flavor:"", snapName:"Human Torch", abilityText:"When this moves, double its Power.", imageUrl:CARD_IMAGES["c056"]||null },
  { id:"c057", name:"Winter St. Cloud", energy:5, clout: 0, abilityId:"  none", flavor:"Totally real foreign exchange student.", snapName:"Iron Man", abilityText:"Ongoing: Your total Power is doubled here.", imageUrl:CARD_IMAGES["c057"]||null },
  { id:"c058", name:"Doordasher", energy:1, clout: 3, abilityId:" spark", flavor:"Always shows up in hand at start of round 2.", snapName:"Iron Fist", abilityText:"On Reveal: After you play your next card, move it one location to the left.", imageUrl:CARD_IMAGES["c058"]||null },
  { id:"c059", name:"John Pork", energy:3, clout: 0, abilityId:"shadow", flavor:"", snapName:"Ironheart", abilityText:"On Reveal: Give 2 of your other cards +3 Power.", imageUrl:CARD_IMAGES["c059"]||null },
  { id:"c060", name:"Tim Cheese", energy:4, clout: 5, abilityId:"  none", flavor:"", snapName:"Jessica Jones", abilityText:"On Reveal: If you don't play a card at this location next turn, +5 Power.", imageUrl:CARD_IMAGES["c060"]||null },
  { id:"c061", name:"Pedro Pascal as Fidel Castro", energy:6, clout: 9, abilityId:"  none", flavor:"Total power equally distributed.", snapName:"The Living Tribunal", abilityText:"Ongoing: Split your total Power evenly among all locations.", imageUrl:CARD_IMAGES["c061"]||null },
  { id:"c062", name:"Detective Oldie", energy:4, clout: 5, abilityId:" surge", flavor:"", snapName:"Juggernaut", abilityText:"On Reveal: Move away all enemy cards played here this turn.", imageUrl:CARD_IMAGES["c062"]||null },
  { id:"c063", name:"Mr. Licorice", energy:4, clout: 6, abilityId:"  none", flavor:"", snapName:"Ka-Zar", abilityText:"Ongoing: Your 1-Cost cards have +1 Power.", imageUrl:CARD_IMAGES["c063"]||null },
  { id:"c064", name:"The Jellybean Gang", energy:3, clout: 3, abilityId:" rally", flavor:"", snapName:"Killmonger", abilityText:"On Reveal: Destroy ALL 1-Cost cards.", imageUrl:CARD_IMAGES["c064"]||null },
  { id:"c065", name:"Mongrel Must", energy:5, clout: 4, abilityId:"  none", flavor:"", snapName:"Klaw", abilityText:"Ongoing: The location to the right has +7 Power.", imageUrl:CARD_IMAGES["c065"]||null },
  { id:"c066", name:"Turt", energy:2, clout: 3, abilityId:"  none", flavor:"", snapName:"Kraven", abilityText:"When a card moves here, this gains +2 Power.", imageUrl:CARD_IMAGES["c066"]||null },
  { id:"c067", name:"The Pickler", energy:3, clout: 5, abilityId:"  none", flavor:"", snapName:"Lady Sif", abilityText:"On Reveal: Discard the card that costs the most from your hand.", imageUrl:CARD_IMAGES["c067"]||null },
  { id:"c068", name:"Sir Squeaks", energy:4, clout: 4, abilityId:"  none", flavor:"", snapName:"Leech", abilityText:"On Reveal: Remove the text from 6-Cost cards in your opponent's hand.", imageUrl:CARD_IMAGES["c068"]||null },
  { id:"c069", name:"Andrew Taint", energy:6, clout:12, abilityId:" drain", flavor:"", snapName:"Magneto", abilityText:"On Reveal: Move all enemy 3 and 4-Cost cards to this location.", imageUrl:CARD_IMAGES["c069"]||null },
  { id:"c070", name:"Decrepit Jimmy Carter", energy:2, clout: 2, abilityId:" spark", flavor:"", snapName:"Mister Sinister", abilityText:"On Reveal: Add a clone here with the same Power.", imageUrl:CARD_IMAGES["c070"]||null },
  { id:"c071", name:"Ascendent Jimmy Carter", energy:6, clout:10, abilityId:" rally", flavor:"", snapName:"Odin", abilityText:"On Reveal: Repeat the On Reveal abilities of your other cards here.", imageUrl:CARD_IMAGES["c071"]||null },
  { id:"c072", name:"Mark Zuckerbark", energy:3, clout: 3, abilityId:"shadow", flavor:"", snapName:"Punisher", abilityText:"Ongoing: +1 Power for each enemy card here.", imageUrl:CARD_IMAGES["c072"]||null },
  { id:"c073", name:"Dan Pills-Aryan", energy:6, clout:10, abilityId:"  none", flavor:"", snapName:"Red Hulk", abilityText:"End of Turn: If your opponent has unspent Energy, +3 Power.", imageUrl:CARD_IMAGES["c073"]||null },
  { id:"c074", name:"Appendix Prince", energy:3, clout: 2, abilityId:"  none", flavor:"", snapName:"Silver Surfer", abilityText:"On Reveal: Give your other 3-Cost cards +2 Power.", imageUrl:CARD_IMAGES["c074"]||null },
  { id:"c075", name:"Ana L'bead", energy:6, clout:12, abilityId:" surge", flavor:"", snapName:"Thanos", abilityText:"Game Start: Shuffle the six Power Stones into your deck.", imageUrl:CARD_IMAGES["c075"]||null },
  { id:"c076", name:"Phenomenal Lucas", energy:2, clout: 0, abilityId:"  none", flavor:"", snapName:"Thena", abilityText:"End of Turn: +3 Power if you played (exactly) 2 cards.", imageUrl:CARD_IMAGES["c076"]||null },
  { id:"c077", name:"Shadowflame", energy:2, clout: 3, abilityId:"shadow", flavor:"", snapName:"Wolverine", abilityText:"When Discarded or Destroyed: Come back with +2 Power at a random location.", imageUrl:CARD_IMAGES["c077"]||null },
];
